# -*- coding: utf-8 -*-
"""Lista1IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16LVbJAVeNZlXKxFhEJfB_XoU-pHLO-Ma
"""

# -*- coding: utf-8 -*-
"""Analise_Marketing.ipynb"""

# ==========================================
# Importações
# ==========================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay

# ==========================================
# 1. Carregamento e Preparação Inicial
# ==========================================
dados = pd.read_csv('marketing.csv')

# Criação das variáveis derivadas
dados['taxa_cliques'] = dados['cliques'] / dados['anuncios']
dados['relevante'] = dados['taxa_cliques'] > 3

# Ordenação para visualização inicial
dados.sort_values(by="taxa_cliques", ascending=False, inplace=True)

# Exibindo o panorama geral do dataset
print("--- Dimensões e Estrutura ---")
print(f"Linhas e Colunas: {dados.shape}\n")
print(dados.info())

print("\n--- Estatísticas Descritivas ---")
print(dados.describe())

# ==========================================
# 2. Análise Exploratória de Dados (EDA)
# ==========================================
# Gráfico de dispersão Anúncios vs Cliques
plt.figure(figsize=(8, 5))
plt.scatter(dados['anuncios'], dados['cliques'], color='teal', alpha=0.7)
plt.title("Relação entre Volume de Anúncios e Cliques Recebidos")
plt.xlabel("Quantidade de Anúncios")
plt.ylabel("Quantidade de Cliques")
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

# Verificação de multicolinearidade e correlação
print("\n--- Matriz de Correlação ---")
print(dados.corr())

# ==========================================
# 3. Divisão dos Dados (Treino e Teste)
# ==========================================
# Isolando a variável preditora (X) e a variável alvo (y)
X = dados[['anuncios']]
y = dados['relevante']

# Separação com proporção de 70/30
X_treino, X_teste, y_treino, y_teste = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42 # Ajustado o seed para uma nova distribuição aleatória
)

# ==========================================
# 4. Treinamento do Modelo
# ==========================================
classificador = LogisticRegression()
classificador.fit(X_treino, y_treino)

# Gerando as predições com o conjunto de teste
previsoes = classificador.predict(X_teste)

# ==========================================
# 5. Avaliação de Performance
# ==========================================
print("\n--- Métricas de Avaliação ---")
print(f"Acurácia do Modelo: {accuracy_score(y_teste, previsoes):.4f}\n")

print("Relatório de Classificação Detalhado:")
print(classification_report(y_teste, previsoes))

# Plotagem da Matriz de Confusão
matriz_confusao = confusion_matrix(y_teste, previsoes)

fig, ax = plt.subplots(figsize=(6, 6))
display_mc = ConfusionMatrixDisplay(
    confusion_matrix=matriz_confusao,
    display_labels=["Irrelevante", "Relevante"]
)
display_mc.plot(cmap="Purples", ax=ax, values_format='d')
plt.title("Matriz de Confusão - Regressão Logística")
plt.show()

